### ISSUE TITLE
When using the deleteVersion method, the disk size increases.

### ISSUE THREAD

**Issue by alexpath** [cosmos/iavl#113]
After each commit, call the deleteVersion function to delete the previous version.

The deletion attempted to reduce the size of the data, but the size increased.

Could you explain why this is happening?

Use version - v0.11.0

Compare size
version:10,000, size:3.1 MB (No delete previous version)
version:10,000, size:4.0 MB (Delete previous version)

**Comment by enlight** [comment]
In my experience you'll need to compact the db after deleting old versions in order to actually reclaim disk space, `leveldb` has a `CompactRange` function you can call with an empty range to compact the whole db.

**Comment by ValarDragon** [comment]
This seems troubling that deleting data is causing _more_ io writes. The size not being reclaimed makes sense, more data being written doesn't seem like it should be the case. I think something is probably wrong here, either from a theoretic perspective, or just implementationally. I also suspect this same problem is likely the underlying cause of https://github.com/cosmos/cosmos-sdk/issues/2131

**Comment by erikgrinaker** [comment]
>This seems troubling that deleting data is causing .9MB (at least) of io writes. The size not being reclaimed makes sense, more data being written doesn't seem like it should be the case.

This isn't necessarily true. LevelDB is log-structured, so deleting a key basically appends an additional log entry like:

```
some_random_key: delete
```

Every database key is a node hash and thus takes up about 40 byte each. It's also possible that orphan/inner node churn amplifies this.

**Comment by tac0turtle** [comment]
this was removed in the last release
