### ISSUE TITLE
enhance dotgraph functionality

### ISSUE THREAD

**Issue by ackratos** [cosmos/iavl#121]
for our usage and on my way implement tendermint state sync (https://github.com/tendermint/tendermint/issues/828), I found dotgraph is helpful while it somehow broken now:
1. node key and values are encoded []byte array, the encoding logic is depends on application, so sometimes they cannot be represented as string, we need show their hex representation on graph.
2. edges cannot be established because the lazy loading of children nodes, we need a set of traversal methods set child along the way we traverse. Currently I just do below on my way of debugging:
```
func (node *Node) getLeftNode(t *ImmutableTree) *Node {
	if node.leftNode != nil {
		return node.leftNode
	}
	node.leftNode = t.ndb.GetNode(node.leftHash)
	return node.leftNode
}

func (node *Node) getRightNode(t *ImmutableTree) *Node {
	if node.rightNode != nil {
		return node.rightNode
	}
	node.rightNode = t.ndb.GetNode(node.rightHash)
	return node.rightNode
}
```

I have already made these changes 80% done on my local machine, will push them soon.

**Comment by marbar3778** [comment]
this is something that came up recently in terms of checkpoint syncing.
