### ISSUE TITLE
Feature/ gRPC Server

### ISSUE THREAD

**Issue by charlescrain** [cosmos/iavl#183]
Hey everyone!

I wanted to start a discussion/make a feature request for adding a gRPC interface to IAVL. 

How difficult would this be to implement?

I'm currently working on a Haskell implementation of the [Cosmos SDK](https://github.com/f-o-a-m/hs-abci) and it would be great to be able to have the SDK use iavl as its key store via the gRPC.

Cheers!
Charles

**Comment by alexanderbez** [comment]
Hey @charlescrain. What does that look like? Is that just an API bridge/layer on top of the existing IAVL API?

**Comment by blinky3713** [comment]
I can volunteer what I know about it. The idea came from working with [google trillian](https://github.com/google/trillian) and writing a [client library](https://github.com/f-o-a-m/hs-trillian) in haskell.

Basically you would write the protobuf descriptions for the api request/response types and define the api itself as a `service` like [this](https://github.com/google/trillian/blob/master/trillian_log_api.proto#L57-L65).  Then you would have to implement the server itself on your end, either in this repo or it could exist as a standalone package.

I think it has advantages in that it allows abci applications in other languages targeting to use the same db as the official cosmos-sdk, in our case allowing a haskell app to talk to a `go` app. Also from a devops perspective it could make things pretty nice to have a separate DB service.

**Comment by alexanderbez** [comment]
I see. Pretty neat. And this would, of course, be an alternative to writing the IAVL library in Haskell? I think we can do this but it would preferable to see this come as a community contribution and have the server as a standalone package.

**Comment by blinky3713** [comment]
> And this would, of course, be an alternative to writing the IAVL library in Haskell
Yes, and really any other language, even if only a stopgap that does emerge in that language

**Comment by blinky3713** [comment]
I would say that we would be able to commit to attempting a server implementation in go, but that when we get to a point we would like help from ya'll in writing the protobuf files to describe the service. What do you think?

**Comment by alexanderbez** [comment]
Sounds great! Let's get started on it. I can start a PR with a single proto type and you can see if this is the correct approach or not before proceeding with the remaining types?

**Comment by blinky3713** [comment]
Ok we're going to take a stab at it. We are not the best `go` developers, but we probably be fine to get something working

**Comment by charlescrain** [comment]
@alexanderbez We've started a repo for the grp server and made an [issue](https://github.com/f-o-a-m/iavl-grpc/issues/1) for getting the protobuf files for all the types and services in one place. 

We'd really appreciate help in getting the protobuf files together to accelerate building this out.

Is there anyone from your side who can work with us on this?

**Comment by alexanderbez** [comment]
@charlescrain let me see what I can do. Would starting a PR in this repo with `/proto` that contains the protobuf definitions help you get started?

**Comment by charlescrain** [comment]
@alexanderbez Yes, that would be great!

**Comment by alexanderbez** [comment]
@charlescrain I've started on the work in PR #184. I have the types and the service nearly complete. After starting work on this, I've realized that having the server implementation separate makes little sense, so I've also implemented the server. In addition, I've also added a gRPC-gateway for JSON HTTP support.

**Comment by marbar3778** [comment]
moving this to 0.14 milestone. most of the work is completed, we just have to push it over the finish line.
