### ISSUE TITLE
IAVL release updates

### ISSUE THREAD

**Issue by marbar3778** [cosmos/iavl#264]
The new tendermint release is bringing countless breaking changes. Some affect this repo:

```
../../../go/pkg/mod/github.com/tendermint/iavl@v0.13.3/proof_iavl_value.go:49:29: undefined: "github.com/tendermint/tendermint/crypto/merkle".ProofOp
../../../go/pkg/mod/github.com/tendermint/iavl@v0.13.3/proof_iavl_value.go:51:9: undefined: "github.com/tendermint/tendermint/crypto/merkle".ProofOp
```

Once Tendermint 0.34 release or pre-release is out then we should update here and do a rc as well. 

This is blocking IAVL release

cc @alexanderbez

**Comment by alexanderbez** [comment]
I didn't even realize IAVL depended on Tendermint. I would vouch to remove the dependency entirely. It seems mostly related to proof types. That seems like a code smell. Can we instead abstract this out or utilize interfaces?

**Comment by marbar3778** [comment]
we can definitely try something like this. I agree that the tm dependency is not needed in this repo

**Comment by marbar3778** [comment]
there are a couple options here:

1. Move `ProofOp` and `ProofOperator` from Tendermint here then have Tendermint rely on IAVL for these types
2. Duplicate the types (mentioned in 1) for now. Assume in the future something will happen. 


This doesn't solve the importing of tmhash. TmHash is a wrapper on sha256 so this would easily be duplicated. In the future when IAVL gets a proper rewrite of sections the authors can decide on which hashing function to use, the same or new.

**Comment by erikgrinaker** [comment]
This is sort of related to the question of what to do about the IAVL proofs as they are still Amino-encoded, see #265.

I'm not sure what the best approach is, but moving them to IAVL and reexporting in Tendermint seems reasonable to me. And probably making them Protobuf-encoded.

As for tm-hash, duplicating should be fine.

**Comment by marbar3778** [comment]
okay seems decided (talked with @alexanderbez, he shares the same sentiment), we move the types here. We wont be able to remove them from tm until IAVL does a release then.
