### ISSUE TITLE
32 bit support?

### ISSUE THREAD

**Issue by Joe-mcgee** [cosmos/iavl#320]
Good day, I'm attempting an install of Thornode on a Raspberry pi 3+b, which is the arm 32 bit architecture.  Its make install command is returning 
```../go/pkg/mod/github.com/tendermint/iavl@v0.14.0/nodedb.go:232:65: constant 9223372036854775807 overflows int```
```../go/pkg/mod/github.com/tendermint/iavl@v0.14.0/repair.go:44:69: constant 9223372036854775807 overflows int```

which, when looking at these files, they explicitly declare 64 bit integers.  I was wondering if support for 32 bit architectures is on your list, or if this is out of scope

Cheers,

**Comment by erikgrinaker** [comment]
Hi! This was fixed in #318, but hasn't made it into a release yet. I can backport it and cut 0.14.2.

**Comment by erikgrinaker** [comment]
0.14.2 is out with a fix: https://github.com/cosmos/iavl/releases/tag/v0.14.2
