### ISSUE TITLE
GRPC support for GetByIndex

### ISSUE THREAD

**Issue by jlandrews** [cosmos/iavl#354]
For my use case (in Haskell via [Kepler](https://github.com/f-o-a-m/kepler)), it would be useful to be able to get the nearest populated key/value for a given search key. This is possible in IAVL with Get returning the index of the next populated key, and then using GetByIndex, but the GRPC layer doesn't have this functionality. The Get method returns an error when the requested key is not found, and there is no GetByIndex method.

I think this could be relatively easily addressed by changing the behavior of the GRPC Get method to better match that of ImmutableTree.Get, and by adding a GRPC GetByIndex method which just directly maps to ImmutableTree.GetByIndex.

**Comment by erikgrinaker** [comment]
This sounds reasonable to me, feel like submitting a PR?

**Comment by jlandrews** [comment]
:+1: #355

**Comment by jlandrews** [comment]
Closed with merge of #355
