### ISSUE TITLE
Can iavl maintain multiple branches like git?

### ISSUE THREAD

**Issue by icexin** [cosmos/iavl#393]
Can iavl maintain multiple branches like git? So that I can continue to write in the historical version and form a new branch version.

If not, what changes need to be made to implement? Thank you!

**Comment by robert-zaremba** [comment]
The current IAVL implementation only supports linear versioning. So, you can get a past version using `tree.GetImmutable(version)`, however you can't commit nor modify it.

It's not that hard to to support branching. You will need to fork this library and:
+ change version version naming and use strings, (eg: branch `y` of version `x` will  be names `x.y`)
+ Update API to use string versions
+ Add `tree.GetMmutable(version, fork_name)` - which will load old version into `MutableTree` and set latest version to `parent_version.fork_name`. Or something like that.

**Comment by robert-zaremba** [comment]
Feel free to reopen this issue if needed.
