### ISSUE TITLE
About write to Lazyloadversion

### ISSUE THREAD

**Issue by icexin** [cosmos/iavl#394]
Lazyloadversion says in the comment `Any writes to a lazy loaded tree may result in unexpected behavior`, what 
 unexpected behavior may happen? Thank you!

**Comment by robert-zaremba** [comment]
I'm not 100% sure, I think it will try to save things form a tree which don't exist (because they were not loaded). Check the `MutableTree.SaveVersion` and `MutableTree.set`  functions.
