### ISSUE TITLE
concurrent tree.versions read and tree.versions write

### ISSUE THREAD

**Issue by summerpro** [cosmos/iavl#441]
The map versions in MultableTree have concurrent reading and writing, which may cause panic

* write function: SaveVersion
```golang
tree.versions[version] = true
```

* read function: VersionExists
```golang
func (tree *MutableTree) VersionExists(version int64) bool {
	return tree.versions[version]
}
```

**Comment by marbar3778** [comment]
this is fixed in 0.17.3
