### ISSUE TITLE
cpu-time: investigate (*iavl.Node).get CPU consumption which shows up in profiles

### ISSUE THREAD

**Issue by odeke-em** [cosmos/iavl#461]
## Summary of Bug
I attached some proprietary continuous profiling code to gaiad and started it, and it is running, from which I collect continuous profiles. The results of the consumption from iavl.Node show lots of time from iavl.Node operations consistently being consumed, across multiple profiles consistently.
![Screen Shot 2020-12-19 at 6 13 23 PM](https://user-images.githubusercontent.com/4898263/102703617-fc5b5800-4225-11eb-9837-1637d3a9894f.png)

Performance issues are (potential) security issues, and solving them always wins for everyone.

## Profile
[gaiad-cpuprof19.pdf](https://github.com/cosmos/cosmos-sdk/files/5720392/gaiad-cpuprof19.pdf)

## Version
At tip 25bb17d

____

## For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by marbar3778** [comment]
cc @ValarDragon this would be included in your work correct?

**Comment by ValarDragon** [comment]
Yeah, my understanding is this is showing the time spent in a seek, of crawling the tree and at each layer doing a file open.

**Comment by marbar3778** [comment]
closing this as we are working on data locality and general clean up of this repo
