### ISSUE TITLE
Fix cleveldb, boltdb, rocksdb and badgerdb tests in CI

### ISSUE THREAD

**Issue by p0mvn** [cosmos/iavl#469]
**Background**

We refactored benchmarks to test all databases in #465  . However, the CI is failing in bencher: https://dashboard.bencher.orijtech.com/benchmark/adc2a152a52245579ef92af91f4f0f74

In #468 we commented out all databases but `memdb` and `goleveldb` to allow bencher to pass.

From the initial investigation, the failure might be due to these additional databases requiring extra setup:
https://github.com/cosmos/iavl/blob/fe24be8d8d97a95c588554299eb045dea116a8a9/benchmarks/setup/INSTALL_ROOT.sh

However, more investigation is needed to determine the true source

**Acceptance Criteria**
- [ ] the root cause of bencher failures is found
- [ ] a PR with the fix is created
- [ ] bencher passes for all databases currently commented out in `bench_test.go`
- [ ] no time out observed

**Comment by marbar3778** [comment]
@faddat I think you did this work?

**Comment by faddat** [comment]
I did, but we are held up on a merge.  

Here's what I'll do to resolve:

Close this PR:
https://github.com/cosmos/iavl/pull/466

Finish implemeting this issue:
https://github.com/cosmos/cosmos-sdk/issues/11688

Make this repository depend on that docker image.

Also, if there are no known usages of iavl outside of the cosmos-sdk, I want to recommend that we move this into cosmos/cosmos-sdk

**Comment by marbar3778** [comment]
Closing as we are migrating to cosmos-db and removed badger and bolt
