### ISSUE TITLE
Support deletion of latest saved version

### ISSUE THREAD

**Issue by yihuang** [cosmos/iavl#482]
When we try to implement the rollback command in cosmos-sdk, we want to delete the latest saved version, but that's not allowed in the current version of iavl, what's the reason for that, and is it possible to relax that restriction?

**Comment by marbar3778** [comment]
@yihuang do you still need this?

**Comment by yihuang** [comment]
> @yihuang do you still need this?

I think LoadVersionForOverwriting do just that, although it's very slow to run in a big db.
