### ISSUE TITLE
release 0.18.1 and 0.17.1

### ISSUE THREAD

**Issue by marbar3778** [cosmos/iavl#491]
- with speed updates

**Comment by marbar3778** [comment]
and a 0.19 with the panic fixes

**Comment by p0mvn** [comment]
Once speed updates are released, I can help with integrating the new release to the SDK.

For reference, this is what was done in the Osmosis fork:
- https://github.com/osmosis-labs/cosmos-sdk/pull/108

**Comment by robert-zaremba** [comment]
It seams some of the updates in osmosis#108 are breaking, so not sure if they can still be released with 0.46

**Comment by marbar3778** [comment]
closing this in favour of releasing 0.19. The reason for 0.19 is due to api breaking changes
