### ISSUE TITLE
refactor: Statistics check for nil in its methods

### ISSUE THREAD

**Issue by p0mvn** [cosmos/iavl#507]
**Background**

We have a [`Statistics`](https://github.com/cosmos/iavl/blob/d696f75d7e085aede83d297cd1f2ccf678345c96/options.go#L6) option that tracks the number of cash hits and misses. It is optional and might not be enabled in `nodedb`.

Therefore, we perform several checks for nil in `GetNode()` and `GetFastNode()` such as:
```
if ndb.opts.Stat != nil {
	ndb.opts.Stat.IncCacheHitCnt()
}
```

Doing these checks multiple times adds verbosity to an already complex `nodedb.go`. Instead, I propose to refactor the following `Statistics` methods:
- `IncCacheHitCnt`
- `IncCacheMissCnt`
- `IncFastCacheHitCnt`
- `IncFastCacheMissCnt`

to do the checks for nil inside the methods such as:
```
func (stat *Statistics) IncCacheHitCnt() {
        if stat == nil {
             return
        }
	atomic.AddUint64(&stat.cacheHitCnt, 1)
}
```

This would allow us to call these methods like the following in `nodedb.go` and improve readability:
```
ndb.opts.Stat.IncCacheHitCnt()
```
- notice no check for nil

**Acceptance Criteria**
- Introduce nil checks within the `Statistics` methods
- remove checks for nil `Statistics` in `nodedb.go`
- all unit tests continue to pass

**Comment by luohaha** [comment]
https://github.com/cosmos/iavl/pull/529
