### ISSUE TITLE
Benchmarks are not working properly

### ISSUE THREAD

**Issue by giskook** [cosmos/iavl#512]
hi,
My ubuntu version is below
```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
```
How to Reproduce the problem
refer to this document：https://github.com/cosmos/iavl/blob/master/benchmarks/README.md
1. I clone  iavl to my machine.
```
git clone https://github.com/cosmos/iavl.git
```
2. go to the setup position
```
cd iavl/benchmarks/setup/
```
3. run the INSTALL_ROOT.sh
```
./INSTALL_ROOT.sh
```
4. run the benchmarks
```
./RUN_BENCHMARKS.sh
```
then I go the error:
```
Cloning into 'iavl'...
remote: Enumerating objects: 6241, done.
remote: Counting objects: 100% (682/682), done.
remote: Compressing objects: 100% (418/418), done.
remote: Total 6241 (delta 433), reused 450 (delta 260), pack-reused 5559
Receiving objects: 100% (6241/6241), 9.43 MiB | 15.96 MiB/s, done.
Resolving deltas: 100% (4062/4062), done.
Already on 'master'
Your branch is up to date with 'origin/master'.
make: *** [bench] Error 1
```
5. I go to the iavl position
```
cd ~/iavl/
```
6. run benchmark
```
make bench
```
then I got the result below:
```
cd benchmarks && \
	go test -ldflags "-X github.com/cosmos/iavl.Version=0.18.0-17-g80bc6e4 -X github.com/cosmos/iavl.Commit=80bc6e464bbbaac360f27ddc570f4511535cfec6 -X github.com/cosmos/iavl.Branch=master" -bench=RandomBytes . && \
	go test -ldflags "-X github.com/cosmos/iavl.Version=0.18.0-17-g80bc6e4 -X github.com/cosmos/iavl.Commit=80bc6e464bbbaac360f27ddc570f4511535cfec6 -X github.com/cosmos/iavl.Branch=master" -tags cleveldb,rocksdb,boltdb,badgerdb -bench=Small . && \
	go test -ldflags "-X github.com/cosmos/iavl.Version=0.18.0-17-g80bc6e4 -X github.com/cosmos/iavl.Commit=80bc6e464bbbaac360f27ddc570f4511535cfec6 -X github.com/cosmos/iavl.Branch=master" -tags cleveldb,rocksdb,boltdb,badgerdb -bench=Medium . && \
	go test -ldflags "-X github.com/cosmos/iavl.Version=0.18.0-17-g80bc6e4 -X github.com/cosmos/iavl.Commit=80bc6e464bbbaac360f27ddc570f4511535cfec6 -X github.com/cosmos/iavl.Branch=master" -bench=BenchmarkMemKeySizes .
iavl: 0.18.0-17-g80bc6e4
git commit: 80bc6e464bbbaac360f27ddc570f4511535cfec6
git branch: master
go version go1.17.6 linux/amd64

goos: linux
goarch: amd64
pkg: github.com/cosmos/iavl/benchmarks
cpu: Intel(R) Xeon(R) Platinum 8375C CPU @ 2.90GHz
BenchmarkRandomBytes/random-4-16         	46490554	        24.76 ns/op
BenchmarkRandomBytes/random-16-16        	31667058	        37.41 ns/op
BenchmarkRandomBytes/random-32-16        	23234440	        51.63 ns/op
BenchmarkRandomBytes/random-100-16       	10534645	       113.5 ns/op
BenchmarkRandomBytes/random-1000-16      	 1285242	       936.5 ns/op
PASS
ok  	github.com/cosmos/iavl/benchmarks	7.125s
iavl: 0.18.0-17-g80bc6e4
git commit: 80bc6e464bbbaac360f27ddc570f4511535cfec6
git branch: master
go version go1.17.6 linux/amd64

Init Tree took 1.11 MB
goos: linux
goarch: amd64
pkg: github.com/cosmos/iavl/benchmarks
cpu: Intel(R) Xeon(R) Platinum 8375C CPU @ 2.90GHz
BenchmarkSmall/memdb-1000-100-4-10/query-no-in-tree-guarantee-fast-16         	 3373084	       354.2 ns/op	      64 B/op	       3 allocs/op
--- FAIL: BenchmarkSmall/memdb-1000-100-4-10/query-no-in-tree-guarantee-slow
    bench_test.go:93:
        	Error Trace:	bench_test.go:93
        	            				bench_test.go:381
        	            				benchmark.go:192
        	            				benchmark.go:232
        	            				asm_amd64.s:1581
        	Error:      	Should be false
        	Test:       	BenchmarkSmall/memdb-1000-100-4-10/query-no-in-tree-guarantee-slow
BenchmarkSmall/memdb-1000-100-4-10/query-hits-fast-16                         	15130903	        79.20 ns/op	       0 B/op	       0 allocs/op
--- FAIL: BenchmarkSmall/memdb-1000-100-4-10/query-hits-slow
    bench_test.go:113:
        	Error Trace:	bench_test.go:113
        	            				bench_test.go:390
        	            				benchmark.go:192
        	            				benchmark.go:232
        	            				asm_amd64.s:1581
        	Error:      	Should be false
        	Test:       	BenchmarkSmall/memdb-1000-100-4-10/query-hits-slow
BenchmarkSmall/memdb-1000-100-4-10/iteration-fast-16                          	    4292	    274672 ns/op	  152498 B/op	    2999 allocs/op
--- BENCH: BenchmarkSmall/memdb-1000-100-4-10/iteration-fast-16
    bench_test.go:156: completed 1000 iterations
    bench_test.go:156: completed 1000 iterations
    bench_test.go:156: completed 1000 iterations
    bench_test.go:156: completed 1000 iterations
    bench_test.go:156: completed 1000 iterations
    bench_test.go:156: completed 1000 iterations
    bench_test.go:156: completed 1000 iterations
    bench_test.go:156: completed 1000 iterations
    bench_test.go:156: completed 1000 iterations
    bench_test.go:156: completed 1000 iterations
	... [output truncated]
BenchmarkSmall/memdb-1000-100-4-10/iteration-slow-16                          	     735	   1626761 ns/op	  819175 B/op	   15796 allocs/op
--- BENCH: BenchmarkSmall/memdb-1000-100-4-10/iteration-slow-16
    bench_test.go:156: completed 1000 iterations
    bench_test.go:156: completed 1000 iterations
    bench_test.go:156: completed 1000 iterations
    bench_test.go:156: completed 1000 iterations
    bench_test.go:156: completed 1000 iterations
    bench_test.go:156: completed 1000 iterations
    bench_test.go:156: completed 1000 iterations
    bench_test.go:156: completed 1000 iterations
    bench_test.go:156: completed 1000 iterations
    bench_test.go:156: completed 1000 iterations
	... [output truncated]
BenchmarkSmall/memdb-1000-100-4-10/update-16                                  	   51558	     25466 ns/op	   12071 B/op	     183 allocs/op
BenchmarkSmall/memdb-1000-100-4-10/block-16                                   	     314	   5650135 ns/op	 2367334 B/op	   36232 allocs/op
--- FAIL: BenchmarkSmall/memdb-1000-100-4-10
Init Tree took 0.72 MB
BenchmarkSmall/goleveldb-1000-100-4-10/query-no-in-tree-guarantee-fast-16     	 1589504	       755.9 ns/op	     120 B/op	       6 allocs/op
--- FAIL: BenchmarkSmall/goleveldb-1000-100-4-10/query-no-in-tree-guarantee-slow
    bench_test.go:93:
        	Error Trace:	bench_test.go:93
        	            				bench_test.go:381
        	            				benchmark.go:192
        	            				benchmark.go:232
        	            				asm_amd64.s:1581
        	Error:      	Should be false
        	Test:       	BenchmarkSmall/goleveldb-1000-100-4-10/query-no-in-tree-guarantee-slow
BenchmarkSmall/goleveldb-1000-100-4-10/query-hits-fast-16                     	15140086	        79.31 ns/op	       0 B/op	       0 allocs/op
--- FAIL: BenchmarkSmall/goleveldb-1000-100-4-10/query-hits-slow
    bench_test.go:113:
        	Error Trace:	bench_test.go:113
        	            				bench_test.go:390
        	            				benchmark.go:192
        	            				benchmark.go:232
        	            				asm_amd64.s:1581
        	Error:      	Should be false
        	Test:       	BenchmarkSmall/goleveldb-1000-100-4-10/query-hits-slow
BenchmarkSmall/goleveldb-1000-100-4-10/iteration-fast-16                      	    2059	    589798 ns/op	  168480 B/op	    4997 allocs/op
--- BENCH: BenchmarkSmall/goleveldb-1000-100-4-10/iteration-fast-16
    bench_test.go:156: completed 1000 iterations
    bench_test.go:156: completed 1000 iterations
    bench_test.go:156: completed 1000 iterations
    bench_test.go:156: completed 1000 iterations
    bench_test.go:156: completed 1000 iterations
    bench_test.go:156: completed 1000 iterations
    bench_test.go:156: completed 1000 iterations
    bench_test.go:156: completed 1000 iterations
    bench_test.go:156: completed 1000 iterations
    bench_test.go:156: completed 1000 iterations
	... [output truncated]
BenchmarkSmall/goleveldb-1000-100-4-10/iteration-slow-16                      	     458	   2601788 ns/op	 1097276 B/op	   23739 allocs/op
--- BENCH: BenchmarkSmall/goleveldb-1000-100-4-10/iteration-slow-16
    bench_test.go:156: completed 1000 iterations
    bench_test.go:156: completed 1000 iterations
    bench_test.go:156: completed 1000 iterations
    bench_test.go:156: completed 1000 iterations
    bench_test.go:156: completed 1000 iterations
    bench_test.go:156: completed 1000 iterations
    bench_test.go:156: completed 1000 iterations
    bench_test.go:156: completed 1000 iterations
    bench_test.go:156: completed 1000 iterations
    bench_test.go:156: completed 1000 iterations
	... [output truncated]
BenchmarkSmall/goleveldb-1000-100-4-10/update-16                              	   33482	     38438 ns/op	   21474 B/op	     184 allocs/op
BenchmarkSmall/goleveldb-1000-100-4-10/block-16                               	     200	   8488533 ns/op	 4255632 B/op	   42457 allocs/op
--- FAIL: BenchmarkSmall/goleveldb-1000-100-4-10
--- FAIL: BenchmarkSmall
FAIL
exit status 1
FAIL	github.com/cosmos/iavl/benchmarks	20.050s
FAIL
Makefile:48: recipe for target 'bench' failed
make: *** [bench] Error 1
```
It seems error occurs on this position， the isFastCacheEnabled should be false:
```
	isFastCacheEnabled, err := t.IsFastCacheEnabled() // to ensure fast storage is enabled
	require.NoError(b, err)
	require.False(b, isFastCacheEnabled) // to ensure fast storage is not enabled
```
----------------------------------
Am I missing something？I expect the correct benchmark result. and how can I help?

**Comment by p0mvn** [comment]
Hi @giskook . Thanks for this issue. Could you let me know if the following PR fixes it?

https://github.com/cosmos/iavl/pull/515

**Comment by giskook** [comment]
> Hi @giskook . Thanks for this issue. Could you let me know if the following PR fixes it?
> 
> #515

Yes, with your banch `make bench` works properly. Thanks ;P

**Comment by giskook** [comment]
Hi @p0mvn . When I use rocksdb. the batch panics.
```
Init Tree took 0.57 MB
BenchmarkSmall/rocksdb-1000-100-4-10/query-no-in-tree-guarantee-fast-16       	  951153	      1295 ns/op	      72 B/op	       7 allocs/op
BenchmarkSmall/rocksdb-1000-100-4-10/query-no-in-tree-guarantee-slow-16       	  428944	      3223 ns/op	     476 B/op	      14 allocs/op
BenchmarkSmall/rocksdb-1000-100-4-10/query-hits-fast-16                       	14625267	        82.67 ns/op	       0 B/op	       0 allocs/op
BenchmarkSmall/rocksdb-1000-100-4-10/query-hits-slow-16                       	fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7feff6734958 pc=0x7feff2235108]

runtime stack:
runtime.throw({0xb0ad87, 0x3a16178})
	/usr/local/go/src/runtime/panic.go:1198 +0x71
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:719 +0x396

goroutine 6503 [syscall]:
runtime.cgocall(0x9560c0, 0xc00006d940)
	/usr/local/go/src/runtime/cgocall.go:156 +0x5c fp=0xc00006d918 sp=0xc00006d8e0 pc=0x421dbc
github.com/tecbot/gorocksdb._Cfunc_rocksdb_create_iterator(0x38f8038, 0x396bde0)
	_cgo_gotypes.go:1162 +0x4d fp=0xc00006d940 sp=0xc00006d918 pc=0x86570d
github.com/tecbot/gorocksdb.(*DB).NewIterator.func1(0x93305f, 0xc0001de7e0)
	/root/go/pkg/mod/github.com/tecbot/gorocksdb@v0.0.0-20191217155057-f0fad39f321c/db.go:499 +0x7d fp=0xc00006d980 sp=0xc00006d940 pc=0x87785d
github.com/tecbot/gorocksdb.(*DB).NewIterator(0xc000050800, 0x0)
	/root/go/pkg/mod/github.com/tecbot/gorocksdb@v0.0.0-20191217155057-f0fad39f321c/db.go:499 +0x19 fp=0xc00006d9a8 sp=0xc00006d980 pc=0x877799
github.com/tendermint/tm-db.(*RocksDB).ReverseIterator(0xc0001de7e0, {0xc000922040, 0x1, 0x9}, {0xc000922050, 0x9, 0x9})
	/root/go/pkg/mod/github.com/tendermint/tm-db@v0.6.6/rocksdb.go:198 +0x85 fp=0xc00006da00 sp=0xc00006d9a8 pc=0x898125
github.com/cosmos/iavl.(*nodeDB).getPreviousVersion(0xc000fc4000, 0xc0019e6000)
	/root/zhangkai/iavl/nodedb.go:765 +0x130 fp=0xc00006dae0 sp=0xc00006da00 pc=0x93f0f0
github.com/cosmos/iavl.(*nodeDB).SaveOrphans(0xc000fc4000, 0x0, 0xa27600)
	/root/zhangkai/iavl/nodedb.go:658 +0xc5 fp=0xc00006dc28 sp=0xc00006dae0 pc=0x93e385
github.com/cosmos/iavl.(*MutableTree).SaveVersion(0xc000f1a000)
	/root/zhangkai/iavl/mutable_tree.go:861 +0x165 fp=0xc00006dde8 sp=0xc00006dc28 pc=0x935565
github.com/cosmos/iavl/benchmarks.runKnownQueriesSlow(0xc0001446c0, 0x4a34d7, {0xc000fcc000, 0x3e8, 0x1226640})
	/root/zhangkai/iavl/benchmarks/bench_test.go:106 +0x52 fp=0xc00006de88 sp=0xc00006dde8 pc=0x951732
github.com/cosmos/iavl/benchmarks.runSuite.func4(0xc0001446c0)
	/root/zhangkai/iavl/benchmarks/bench_test.go:390 +0x34 fp=0xc00006dec0 sp=0xc00006de88 pc=0x953fd4
testing.(*B).runN(0xc0001446c0, 0x64)
	/usr/local/go/src/testing/benchmark.go:192 +0x126 fp=0xc00006df40 sp=0xc00006dec0 pc=0x515a66
testing.(*B).launch(0xc0001446c0)
	/usr/local/go/src/testing/benchmark.go:328 +0x1c5 fp=0xc00006dfc8 sp=0xc00006df40 pc=0x516645
testing.(*B).doBench·dwrap·4()
	/usr/local/go/src/testing/benchmark.go:283 +0x26 fp=0xc00006dfe0 sp=0xc00006dfc8 pc=0x516446
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00006dfe8 sp=0xc00006dfe0 pc=0x486561
created by testing.(*B).doBench
	/usr/local/go/src/testing/benchmark.go:283 +0x7b

goroutine 1 [chan receive]:
testing.(*B).run1(0xc0000d66c0)
	/usr/local/go/src/testing/benchmark.go:234 +0xbb
testing.(*B).Run(0xc000144000, {0xaf55b6, 0x3d0b94b7fb362a}, 0xb1d6b0)
	/usr/local/go/src/testing/benchmark.go:670 +0x438
testing.runBenchmarks.func1(0xc000144000)
	/usr/local/go/src/testing/benchmark.go:544 +0x6e
testing.(*B).runN(0xc000144000, 0x1)
	/usr/local/go/src/testing/benchmark.go:192 +0x126
testing.runBenchmarks({0xb041ee, 0x21}, 0x0, {0x1199d00, 0x7, 0xaf5ce0})
	/usr/local/go/src/testing/benchmark.go:553 +0x3e6
testing.(*M).Run(0xc00011e080)
	/usr/local/go/src/testing/testing.go:1510 +0x6d6
main.main()
	_testmain.go:55 +0x14b

goroutine 24 [chan receive]:
testing.(*B).run1(0xc000144480)
	/usr/local/go/src/testing/benchmark.go:234 +0xbb
testing.(*B).Run(0xc0000d66c0, {0xc000026108, 0x0}, 0xc000fc2410)
	/usr/local/go/src/testing/benchmark.go:670 +0x438
github.com/cosmos/iavl/benchmarks.runBenchmarks(0xc0000d66c0, {0xc0000abeb0, 0x2, 0xb1f458})
	/root/zhangkai/iavl/benchmarks/bench_test.go:349 +0x67e
github.com/cosmos/iavl/benchmarks.BenchmarkSmall(0xc0000d66c0)
	/root/zhangkai/iavl/benchmarks/bench_test.go:281 +0xd7
testing.(*B).runN(0xc0000d66c0, 0x1)
	/usr/local/go/src/testing/benchmark.go:192 +0x126
testing.(*B).run1.func1()
	/usr/local/go/src/testing/benchmark.go:232 +0x59
created by testing.(*B).run1
	/usr/local/go/src/testing/benchmark.go:225 +0xa5

goroutine 6500 [chan receive]:
testing.(*B).doBench(0xc0001446c0)
	/usr/local/go/src/testing/benchmark.go:284 +0x8e
testing.(*benchContext).processBench(0xc000120048, 0x230)
	/usr/local/go/src/testing/benchmark.go:583 +0x3aa
testing.(*B).run(0xc0001446c0)
	/usr/local/go/src/testing/benchmark.go:275 +0x67
testing.(*B).Run(0xc000144480, {0xaf6677, 0xafc937}, 0xc00051c000)
	/usr/local/go/src/testing/benchmark.go:671 +0x446
github.com/cosmos/iavl/benchmarks.runSuite(0xc000144480, {0xbc4e90, 0xc003572120}, 0x3e8, 0x64, 0x4, 0xa)
	/root/zhangkai/iavl/benchmarks/bench_test.go:388 +0x30d
github.com/cosmos/iavl/benchmarks.runBenchmarks.func2(0xc000144480)
	/root/zhangkai/iavl/benchmarks/bench_test.go:350 +0x31
testing.(*B).runN(0xc000144480, 0x1)
	/usr/local/go/src/testing/benchmark.go:192 +0x126
testing.(*B).run1.func1()
	/usr/local/go/src/testing/benchmark.go:232 +0x59
created by testing.(*B).run1
	/usr/local/go/src/testing/benchmark.go:225 +0xa5
exit status 2
FAIL	github.com/cosmos/iavl/benchmarks	18.880s
FAIL
Makefile:48: recipe for target 'bench' failed
make: *** [bench] Error 1
```

**Comment by giskook** [comment]
Hi @p0mvn . If I want to get the benefits of iavl fast storage, how can I update the underlying storage to fast cache?

**Comment by p0mvn** [comment]
Hi @giskook . It should work by default and out of the box, once released.

I don't think it's officially released yet. To experiment, you would have to checkout the master branch and use a replace directive in the project depending on IAVL to point to your local copy.

In terms of the details of how the underlying storage gets converted to fast, the first time you run the updated IAVL, it will create an additional "fast" index on disk for the latest height with data locality preserved. This "fast" index is what makes the storage faster than before.  

Again, no extra action needed is needed. The index should be auto-created/migrated to the first time you run the updated IAVL. The upgrade should take a few minutes and you would see several log messages "Upgrading to fast IAVL...".

Please let me know if you have more questions.

**Comment by giskook** [comment]
> Hi @giskook . It should work by default and out of the box, once released.
> 
> I don't think it's officially released yet. To experiment, you would have to checkout the master branch and use a replace directive in the project depending on IAVL to point to your local copy.
> 
> In terms of the details of how the underlying storage gets converted to fast, the first time you run the updated IAVL, it will create an additional "fast" index on disk for the latest height with data locality preserved. This "fast" index is what makes the storage faster than before.
> 
> Again, no extra action is needed. The index should be auto-created/migrated to the first time you run the updated IAVL. The upgrade should take a few minutes and you would see several log messages "Upgrading to fast IAVL...".
> 
> Please let me know if you have more questions.

Hi @p0mvn ,

It sounds great! I benchmark with 3,000,000 key-value pair.It shows:

1. Query with no guarantee of the key being in the tree:  fast logic shows a **56.99% decrease** in time relative to the slow one.
2. Query with the key guaranteed to be in the latest tree: fast logic shows a **78.73% decrease** in time relative to the slow one.  
```
BenchmarkLarge/goleveldb-3000000-100-16-40/query-no-in-tree-guarantee-fast-16                 6369            353760 ns/op            1027 B/op              20 allocs/op
BenchmarkLarge/goleveldb-3000000-100-16-40/query-no-in-tree-guarantee-slow-16                 1359            822428 ns/op           18728 B/op             131 allocs/op
BenchmarkLarge/goleveldb-3000000-100-16-40/query-hits-fast-16                                 5623            179241 ns/op            1151 B/op              22 allocs/op
BenchmarkLarge/goleveldb-3000000-100-16-40/query-hits-slow-16                                 1317            884184 ns/op           16898 B/op             116 allocs/op
PASS
```

I check our chain's pprof, the `ImmutableTree.Get` take about 25% cpu time. Based on the benchmark fast cache imporve performance so much. so if I migration fast code. the cpu time will decrease to about  25%*56.99% = 14.24% ? It's a huge improvement. Am i missing something?

**Comment by giskook** [comment]
Hi @p0mvn ,

**Comment by p0mvn** [comment]
> 25%*56.99% = 14.24%

I don't think this would be an exact value but a very rough approximation. This is because the fast index only improves queries and iterations to the latest state. Queries and iterations to the old state utilize the same logic as before and are not expected to provide any performance benefits. Note, that accessing the latest state is much more common on cosmos-sdk-based chains than the old state. That's why this approximation might suffice in most cases.

In Osmosis, where we have been running this for a few months now, we have a concept of epochs that utilize some database-intensive logic once per day. Some folks profiled and compared epoch logic on live nodes with and without fast IAVL and here are [the results](https://twitter.com/JoeAbbey/status/1491830953936834569?s=20&t=Wey1nw7XP7TWPSq69xBVrg).

Speaking of benchmarks, `query-no-in-tree-guarantee-slow` utilizes the logic that has been used historically in IAVL. However, while implementing the fast index, some minor changes were introduced that might make the performance vary slightly from older IAVL versions.

If you are looking for the most accurate benchmark results relative to your current IAVL version, I would recommend checking out the tag that you are currently using on your chain.

For example, you can use these benchmarks on the `v0.18.0` tag:
https://github.com/cosmos/iavl/blob/ccfb418465fe10c16ec7cd96aebbf53ae66b636a/benchmarks/bench_test.go#L290-L297

`query-miss` on any old IAVL tag can be compared to the following on `master`:
 - `query-no-in-tree-guarantee-fast` - when query goes to latest state (latest height)
 - `query-no-in-tree-guarantee-slow` - when query goes to the old state

Similarly,

`query-hits` before can be compared to current:
- `query-hits-fast`
- `query-hits-slow`

The benchmark name changes make it more difficult to evaluate but this is the only way since the state and its handling logic are now split into two:
1. latest state (fast index)
2. non-latest state (slow or regular logic that has been historically used in IAVL) 

In my opinion, the described comparison is the most accurate you can get relative to the current version of IAVL that you are using.

Also, I've already compared the `fast` queries and iterations to `v0.17.3` queries and iterations by renaming the benchmarks to the same names here:
https://github.com/cosmos/iavl/pull/468#issuecomment-1041078297

**Comment by giskook** [comment]
> Also, I've already compared the `fast` queries and iterations to `v0.17.3` queries and iterations by renaming the benchmarks to the same names here: [#468 (comment)](https://github.com/cosmos/iavl/pull/468#issuecomment-1041078297)
Hi @p0mvn , 
I have read the #468, it says
```
The fast storage nodes are instead indexed by the logical key on the disk. 
This allows us to preserve data locality for the latest state,
 significantly improving iterations and queries. 
(Depending on the particular benchmark, between 5-30x improvements)
 This implementation introduces a negligible overhead for writes.
```
Now I want to ask more about `data locality`, Operating systems have become increasingly aggressive in their use of main memory for disk caching，and it provides read-ahead and write-behind techniques that prefetch data in large block multiples and group smaller logical writes into large physical writes.  
1. Does the `data locality` mean this?
2. Our logical key maybe `f<keystring0>` and `f<keystring10000>`, after get the `k<keystring0>` it depends on the OS whether or not the `f<keystring10000>` in the cache? maybe the key `f<keystring10000>` we will call direct to the disk?
3. If we use a independent db to store the key/value. what's the different with the `data locality`

**Comment by giskook** [comment]
> Please let me know if you have more questions.

Hi @p0mvn ,
Before I try to migrate the code to our chain,I have a few questions.Hope hear from you ;P
1. why `fast node on disk` and `live state` may [mismatch](https://github.com/cosmos/iavl/blob/master/mutable_tree.go#L644)?Is it will persisting the stale state?
2. After I upgrade my code, how can I disable the feature?  It seems when I upgrade to `fastStorageVersionValue`, I can not roll back to the `defaultStorageVersionValue`?
3. As we store the fast node, how much  disk space will it take up?

**Comment by p0mvn** [comment]
Hi @giskook 

1. There should never be a mismatch between the two. The part of the code that you linked is actually an edge-case prevention mechanism. This edge case might happen if a node operator attempts to downgrade and then re-upgrade. Therefore, we added an additional layer of downgrade + re-upgrade protection. Basically, if IAVL detects that there is a mismatch between the fast and live state during start-up, we delete all of the fast nodes and re-create them from the actual live state. As a result, it should be impossible to have a mismatch post-start-up.

2. The only way to disable it is by downgrading to an older version of IAVL. This change is backward compatible as it only adds an additional index. No foundational logic about how the data is stored has been changed.

3. Unfortunately, I could not find my original benchmarks for this. From my memory, the growth was pretty minor on the Osmosis chain - under 3 Gb. You should be able to test this on the mainnet of your chain for the most accurate results by simply spinning up a full node that utilizes the new IAVL. There are no state-breaking changes from swapping out IAVL.

Hope this helps

**Comment by giskook** [comment]
Hi @p0mvn ,

We have migrated fast storage to our chain, it works perfect. but  it seems every time I restart the chain, I need rebuild the index.Is it in line with expectations? I think if we already have the fast-index, then we do not need to rebuild it again.

Thanks in advance

**Comment by giskook** [comment]
> Hi @giskook .
> 
> This is currently expected. In some cases, the rebuilding might be redundant and its frequency can be reduced in the future. However, for safety, we went with the approach of rebuilding more often than needed.

Hi @p0mvn ,
What are the safety reasons for needing to rebuild indexes? Have you met? Our chain data is huge and it takes hours to rebuild at a time, so rebuilding costs are high.
