### ISSUE TITLE
#468 bug report

### ISSUE THREAD

**Issue by Ywmet** [cosmos/iavl#520]
### mutable_tree.go
![image](https://user-images.githubusercontent.com/6890141/177906954-48b44489-de77-4275-8655-4ae21bd74749.png)
after get from unsavedFastNodeAdditions need to read from unsavedFastNodeRemovals

### eg:
```
func (tree *MutableTree) Get(key []byte) []byte {
	if tree.root == nil {
		return nil
	}

	if fastNode, ok := tree.unsavedFastNodeAdditions[string(key)]; ok {
		return fastNode.value
	}
        if fastNode, ok := tree.unsavedFastNodeRemovals[string(key)];ok {
                 //if deleted 
                 return nil
        }

	return tree.ImmutableTree.Get(key)
}
```

**Comment by p0mvn** [comment]
Thank you for the report @Ywmet 

I think the proposed approach works and should be implemented. This has gone uncaught because, as far as I know, sdk never reads from the mutable tree. Instead, it reads from the immutable tree that has state already committed.
