### ISSUE TITLE
Add regression tests for proof format

### ISSUE THREAD

**Issue by marbar3778** [cosmos/iavl#569]
As we begin spending more time onboarding to iavl and modifying it we should write test vectors and regression tests to make sure things are how they are suppose to be

**Comment by facundomedica** [comment]
Q: how those proof regression tests would be different from these? https://github.com/cosmos/iavl/blob/master/proof_iavl_test.go#L14-L41

**Comment by marbar3778** [comment]
ah didnt know those were there. this came from a talk with Ethan frey
