### ISSUE TITLE
Modify the key format from a hash of the data to be `write_version|node_path_in_tree`

### ISSUE THREAD

**Issue by cool-develope** [cosmos/iavl#571]
ref: #548

**Comment by marbar3778** [comment]
@catShaark want to collaborate with @cool-develope on this work? I see you started the work alreadt

**Comment by catShaark** [comment]
Yes I do

**Comment by cool-develope** [comment]
@catShaark, I couldn't follow your approach. We can get children's paths through the parent path.
```go
// Node represents a node in a Tree.
type Node struct {
	key           []byte
	value         []byte
	hash          []byte
	version       int64
	size          int64
	path          []byte // the path of binary tree
	leftVersion   int64 // the version of left child
	rightVersion  int64 // the version of right child
	leftNode      *Node
	rightNode     *Node
	subtreeHeight int8
	persisted     bool
}
```

**Comment by cool-develope** [comment]
If we use the node key as `path_of_tree | version`, we can't interact with rotate.
When balancing the tree, the tree would be restructured and we should update all restructured nodes in DB. It's too expensive.

I am suggesting the alternative way, instead of ``path_of_tree | version` we will use `updated_order_number`, refer to the below diagram. I assumed LRU (least recently used) algorithm is applied here. If so, it will improve access performance.
![image](https://user-images.githubusercontent.com/51834436/194072739-ca583403-b47d-463e-b611-83a8cbe61482.png)
cc @marbar3778

**Comment by catShaark** [comment]
> If we use the node key as `path_of_tree | version`, we can't interact with rotate. When balancing the tree, the tree would be restructured and we should update all restructured nodes in DB. It's too expensive.

I don't think we need to, we can simply have a field to store the old key and the left and right node's old key

**Comment by alexanderbez** [comment]
I'm not really following the proposal here, but I thought the entire point was that the keys on disk are prefixed with height/version. This makes layout on disk much more efficient.

**Comment by marbar3778** [comment]
This conversation got me thinking it would be good to capture both approaches in an adr.

**Comment by catShaark** [comment]
I think the 2 approaches don't differ much, either way we need to add NodeKey, LeftChildNodeKey, RightChildNodeKey field to the Node struct and have the node saving, key/value setting logic, ... to handle/use those field

**Comment by ValarDragon** [comment]
Got an explanation from Marko (Agreed prior post doesn't explain this well. Next time please include example keys!) Also what exactly are you calling an LRU algorithm?

Doing things off of a write nonce does not make sense to me. This is bad for data locality of a key across versions?

Also I think the whole framing around pivots is pretty off, just model a pivot as a new set of writes?

**Comment by cool-develope** [comment]
I updated the diagram. Here LRU means we will re-visit the recently updated nodes probably.
I agree with @alexanderbez , `Nonce` almost is similar to `version|height`. It requires `n * log(n)` space but `version|path` require `n * n` space. To reduce the size of the node struct, I vote `version|height` structure. as @ValarDragon mentioned, we need to add `leftChildVersion` and `rightChildVersion`.

**Comment by marbar3778** [comment]
@cool-develope your suggestion seems in line with this issue https://github.com/cosmos/iavl/issues/137

**Comment by cool-develope** [comment]
> @cool-develope your suggestion seems in line with this issue #137

Yeah, it's almost the same. 
I realized that `version|height` model also doesn't work. Because when balancing the tree, we may have nodes with the same height.
The `Nonce` model is not about using once and throwing away. As you can see in the above diagram, it represents all nodes including orphans. Also, it doesn't destroy any data locality.
