### ISSUE TITLE
Proof: Remove RangeProofs in favour of only ics23 

### ISSUE THREAD

**Issue by tac0turtle** [cosmos/iavl#584]
The current proof system of IAVL is hard to understand and led to a recent hack for Binance. 

Since this code is not actively used in the cosmos-sdk, we should not keep it around. We should look at adopting ics23 natively onto the tree and remove the current proof system.

**Comment by ebuchman** [comment]
I think we can just remove all RangeProof related code and functions. The existing GetMembershipProof and GetNonMembershipProof methods already return the ics23.CommitmentProofs, so we can keep using those.

**Comment by ebuchman** [comment]
Oh I see: https://github.com/cosmos/iavl/issues/284. We can start by just unexporting the RangeProof, and then work towards computing it as an ics23 thing directly rather than converting.
