### ISSUE TITLE
Modify the key format of node in DB to a sequential integer ID instead of the hash value.

### ISSUE THREAD

**Issue by cool-develope** [cosmos/iavl#592]
## Context
As we discussed in #571, I am introducing the `nonce` mechanism here.

- [x] add `nodeKey` field to replace the key of a node in DB
- [x] replace  a key in DB  from `node.hash` to `nodeKey` 
- [ ] investigate the possibility of removing `version` in the node structure

## Design Decision
- immutable tree structure
```go
type ImmutableTree struct {
	root                   *Node
	ndb                    *nodeDB
	version                int64
	nonce                  int64             // new field to track the current ID
	skipFastStorageUpgrade bool
}
```

- node structure
```go
type Node struct {
	key           []byte
	value         []byte
	hash          []byte

	leftHash      []byte        
	rightHash     []byte    

	nodeKey       int64         // new field which reflects the current node key
	leftNodeKey   int64       // new field
	rightNodeKey  int64      // new field

	version       int64           // possible to remove ???

	size          int64
	leftNode      *Node
	rightNode     *Node
	subtreeHeight int8
	persisted     bool
}
```

**Comment by cool-develope** [comment]
> Before the final merge we should have an adr on the chnage

Yeah, I will prepare the adr when finishing all subtasks.

**Comment by catShaark** [comment]
I don't think we should remove leftHash and rightHash. 
How can I collab with you on this ? I already had the code with the changes mentions here, I've modified methods like balance, delete, save branch ..... so that their logic matches with the new node struct, node saving mechanism.
