### ISSUE TITLE
`skipFastStorageUpgrade` a little confusing to followup

### ISSUE THREAD

**Issue by leejw51crypto** [cosmos/iavl#615]
how about changing to `useLegacyStorage` ? 
or other word which not uses `skip`

**Comment by faddat** [comment]
NO.  The whole thing is wrong and causing cascading failures.

**Comment by tac0turtle** [comment]
@faddat please a provide a test case via a go test so we can have regression tests once if we remove it

**Comment by tac0turtle** [comment]
closing this as fast node will be removed in the next release
