### ISSUE TITLE
Restructure repository / packages

### ISSUE THREAD

**Issue by liamsi** [cosmos/iavl#62]
Currently, every file lives in the root directory. We need to refactor the code such that different logical parts live in different packages. This will also help clarifying the exposed API.

**Comment by erikgrinaker** [comment]
I don't think we should do this. We might consider it for internal code (which should go in the special [`internal` package](https://golang.org/cmd/go/#hdr-Internal_Directories)), but I find it ergonomic and idiomatic to keep libraries like these in a single package - see e.g. BadgerDB, BoltDB, and Google B-tree as examples of Go data stores which also do this.

**Comment by marbar3778** [comment]
closing this as IAVL is partially in maintenance, no need to change things up
