### ISSUE TITLE
LoadVersionForOverwriting doesn't commit

### ISSUE THREAD

**Issue by RavenXce** [cosmos/iavl#639]
LoadVersionForOverwriting doesn't actually commit if fast node disabled: https://github.com/cosmos/iavl/blob/c64ca70ffa771de329b0e1a460594e57c4e03555/mutable_tree.go#L628

This also means cosmos-sdk rollback still doesn't work in all cases: https://github.com/cosmos/cosmos-sdk/pull/11361

**Comment by yihuang** [comment]
I think it's fixed in current version

**Comment by RavenXce** [comment]
Looks fixed
