### ISSUE TITLE
Update / improve godoc

### ISSUE THREAD

**Issue by liamsi** [cosmos/iavl#69]
As part of the spec writing work, it would be nice to update and improve the golang documentation. 

Current state is here: http://localhost:6060/pkg/github.com/tendermint/iavl/

**Comment by silasdavis** [comment]
I can't get at your localhost :)

I think we should make a few more specific bitesized documentation tickets (e.g. document file) and then close this one in favour of them.

These ticket might be good a bedfellow with #62

**Comment by faddat** [comment]
Using godoc everywhere just makes sense.
