### ISSUE TITLE
export: don't support multiple formats

### ISSUE THREAD

**Issue by yihuang** [cosmos/iavl#701]
There are some low hanging fruits to compress the exported snapshot format (#690, #688), but before that, we need some refactoring to support multiple formats, so the user can handle the format migration gracefully.
On the IAVL side, we'll just support new formats in an fully additive way, and always support importing from old formats, so it'll be a non-breaking change, and left cosmos-sdk to figure out the format migration process in state-sync.

## Serialization Format

I think we should maintain the serialization format of `ExportNode` inside IAVL library, and provides a bytes oriented import/export interfaces, so it has more control on the exact format.

**Comment by yihuang** [comment]
An alternative is keeping iavl library simple, and do this in cosmos-sdk.

**Comment by tac0turtle** [comment]
The interface on how to do snapshots should live in the sdk since commitment structures could change in the future. Having the api live there makes more sense across commitment structures

**Comment by yihuang** [comment]
> The interface on how to do snapshots should live in the sdk since commitment structures could change in the future. Having the api live there makes more sense across commitment structures

I opened a PR to introduce the compact snapshot in purely new API, totally non-breaking: https://github.com/cosmos/iavl/pull/703, let's leave the other concerns to the sdk side then.
