### ISSUE TITLE
Implement a `lazy set` for the migration to the new node key format

### ISSUE THREAD

**Issue by cool-develope** [cosmos/iavl#747]
## Context
The migration to the new node key format is tricky. To avoid stopping the network, it introduces a `lazy set`. We will accept the existence of both new and old format nodes in the tree.

## Proposal

- Refactor the `Node` structure to accept both old and new nodes, like this

```go
// Node represents a node in a Tree.
type Node struct {
	key           []byte
	value         []byte
	hash          []byte
	nodeKey       *NodeKey
	leftNodeKey   []byte  // it can be a node hash for the old node and be a node key serialization for the new node.
	rightNodeKey  []byte
	size          int64
	leftNode      *Node
	rightNode     *Node
	subtreeHeight int8
}
```

- Setting new nodes will store the node as a new node key format. It will refactor them to the new format for old nodes that face while updating the tree.

**Comment by yihuang** [comment]
Sounds great, so there are just different versions of node key, new version could reference old version, but not the other way.

**Comment by cool-develope** [comment]
> Sounds great, so there are just multiple versions of node key, new version could reference old version, but not the other way.

exactly
