### ISSUE TITLE
Drop error result from Node.hashWithCount

### ISSUE THREAD

**Issue by elias-orijtech** [cosmos/iavl#757]
`Node.hashWithCount` can only return errors in two cases:

https://github.com/cosmos/iavl/blob/64ffc2749400f762d6279db0fd1ccc2b22e69492/node.go#L336-L343

The first case is its own error result, recursively. The second one is the error result from `hash.Hash.Write` which is documented to never return an error.

CC @odeke-em

**Comment by tac0turtle** [comment]
want to submit a pr?
