### ISSUE TITLE
Post-order snapshot

### ISSUE THREAD

**Issue by cool-develope** [cosmos/iavl#852]
IAVL v1 and v0 export is based on post-order, implement post-order export for compatibility with IAVL v0 and v1

**Comment by tac0turtle** [comment]
should we only do restore for post order that way its less code to maintain over the long term?

**Comment by yihuang** [comment]
https://github.com/cosmos/iavl/pull/703

This compact format rely on post-order BTW.

**Comment by tac0turtle** [comment]
we should evaluate which is overall better (compact and performant). I dont think we should support both in iavlv2, only one will get used in reality. This can come later

**Comment by cool-develope** [comment]
with #853
