### ISSUE TITLE
Change IAVL node.writeBytes to take in bytes.Buffer

### ISSUE THREAD

**Issue by ValarDragon** [cosmos/iavl#891]
Every usage of node.WriteBytes we use takes in an io.Writer, not a bytes.Buffer.

We currently are spending 2.1 seconds out of a 2000 block sync on getting and returning buffer pools in node.WriteBytes. (Due to PutVarint calls) I think we should be able to remove this time entirely, by making PutVarint methods that just call bytes.Buffer.WriteByte directly, rather than using a slice from the sync.Pool and then using the generic io.Writer(WriteBytes) which is a second memmove.

**Comment by odeke-em** [comment]
@ValarDragon please take a look at https://github.com/cosmos/iavl/pull/917

**Comment by ValarDragon** [comment]
Thanks for fixing/speeding this up!
