### ISSUE TITLE
GitHub releases are outdated

### ISSUE THREAD

**Issue by Pitasi** [cosmos/iavl#981]
As this repo gets more and more used I think it's important to keep the Releases page on GitHub in sync with the actual tags of the repo.

In particular, I currently see that the latest release on GitHub is v1.1.0 (which has been retracted). So, it's missing v1.2.0 and the newer v1.1.x versions.

Publishing releases allows people like me to be notified by GitHub 😁

**Comment by julienrbrt** [comment]
True, we should add goreleaser.
